# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mywebsite',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/mywebsite',
                'lib_path': 'mywebsite'},
  'syms': {'mywebsite.core': {'mywebsite.core.foo': ('core.html#foo', 'mywebsite/core.py')}}}
